
--What is the total revenue generated by male vs female customers?
SELECT gender,sum(purchase_amount) AS total_revenue
FROM  project2
GROUP BY gender

--Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id ,discount_applied,purchase_amount,(SELECT avg(purchase_amount) FROM project2) AS avg_all
FROM project2 
WHERE (purchase_amount>(SELECT avg(purchase_amount) FROM project2)) AND (discount_applied='Yes')

--Which are the top 5 products WITH the highest average review rating?
SELECT item_purchased,round(avg(review_rating),3) AS avg_review_rating
FROM project2 
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5

--Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,round(avg(purchase_amount),2) AS avg_purchase_amount_of_shipping_type
FROM project2 
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type

--Do subscribed customers spEND more? Compare average spEND and total revenue between subscribers and non-subscribers.
SELECT 	subscription_status,
		count(customer_id) AS total_customers,
		round(avg(purchase_amount),2) AS avg_purchase_amount,
        sum(purchase_amount) AS total_revenue
FROM project2
GROUP BY subscription_status

--Which 5 products have the highest percentage of purchases WITH discounts applied?
SELECT 	item_purchased,
		round(100*sum(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM project2
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5

--Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH cte AS (
  	SELECT customer_id,
  	previous_purchases,
	CASE 
  		WHEN previous_purchases=1 then 'New'
  		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
  		ELSE 'Loyal' 
  		END AS customer_segment
  	FROM project2
)

SELECT customer_segment,count(*) as customer_count
FROM cte
GROUP BY customer_segment

--What are the top 3 most purchased products WITHin each category?
WITH cte AS(
SELECT 	item_purchased,
		category,
        count(customer_id) as total_customer,
        row_number() over (partition by category ORDER BY count(customer_id) DESC) as Rank_item
FROM project2
GROUP BY item_purchased,category
)

SELECT category,item_purchased,total_customer
FROM cte 
WHERE Rank_item<4

--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 	subscription_status,
		COUNT(customer_id) AS total_repeat_customer
		
FROM project2
WHERE previous_purchases>5
GROUP BY subscription_status

--What is the revenue contribution of each age group?
SELECT 	age_group,
		sum(purchase_amount) AS total_revenue_contribution
FROM project2
GROUP BY age_group
ORDER BY total_revenue_contribution DESC


		





