
--What is the total revenue generated by male vs female customers?
SELECT gender,sum(purchase_amount) as total_revenue
from project2
GROUP BY gender

--Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id ,discount_applied,purchase_amount,(SELECT avg(purchase_amount) from project2) as avg_all
from project2 
where (purchase_amount>(SELECT avg(purchase_amount) from project2)) and (discount_applied='Yes')

--Which are the top 5 products with the highest average review rating?
SELECT item_purchased,round(avg(review_rating),3) as avg_review_rating
from project2 
group by item_purchased
ORDER by avg_review_rating DESC
LIMIT 5

--Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(avg(purchase_amount),2) as avg_purchase_amount_of_shipping_type
from project2 
WHERE shipping_type in ('Express','Standard')
group by shipping_type

--Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select 	subscription_status,
		count(customer_id) as total_customers,
		round(avg(purchase_amount),2) as avg_purchase_amount,
        sum(purchase_amount) as total_revenue
from project2
GROUP By subscription_status

--Which 5 products have the highest percentage of purchases with discounts applied?
select 	item_purchased,
		round(100*sum(case when discount_applied='Yes' then 1 ELSE 0 end)/count(*),2) as discount_rate
from project2
group by item_purchased
order by discount_rate desc
LIMIT 5

--Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH cte as (
  	SELECT customer_id,
  	previous_purchases,
	case 
  		WHEN previous_purchases=1 then 'New'
  		WHEN previous_purchases BETWEEN 2 and 10 then 'Returning'
  		else 'Loyal' 
  		end as customer_segment
  	from project2
)

select customer_segment,count(*) as customer_count
from cte
GROUP by customer_segment

--What are the top 3 most purchased products within each category?
with cte as(
select 	item_purchased,
		category,
        count(customer_id) as total_customer,
        row_number() over (partition by category order by count(customer_id) desc) as Rank_item
from project2
group by item_purchased,category
)

SELECT category,item_purchased,total_customer
from cte 
where Rank_item<4

--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select 	subscription_status,
		count(customer_id) as total_repeat_customer
		
from project2
where previous_purchases>5
GROUP by subscription_status

--What is the revenue contribution of each age group?
SELECT 	age_group,
		sum(purchase_amount) as total_revenue_contribution
from project2
group by age_group
ORDER by total_revenue_contribution desc


		




